spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cliente?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: omd123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update